name: Run tests
on:
    pull_request:
        types: [opened, synchronize]

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref }}
    cancel-in-progress: true

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: 8.0.x

            - name: Install dependencies
              run: dotnet restore

            - name: Build
              run: dotnet build --no-restore --configuration Release

            - name: Run tests
              run: dotnet test
                  --no-build
                  --configuration Release
                  --verbosity normal
                  /p:CollectCoverage=true
                  /p:CoverletOutputFormat=lcov
                  /p:CoverletOutput=./TestResults/

            - name: Upload test results
              uses: codecov/codecov-action@v4
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}

            - name: Lint
              id: lint
              continue-on-error: true
              run: dotnet format --verify-no-changes


            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Build the Docker image
              uses: docker/build-push-action@v3
              with:
                  push: false
                  context: "{{defaultContext}}:mohaymen-codestar-Team02"
                  tags: mohaymen-codestar-team02
                  labels: 
